//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_10_mvc_auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_Order { get; set; }
        public Nullable<int> id_Client_FK { get; set; }
        public Nullable<int> id_Bus_FK { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> cost { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Client Client { get; set; }
    }
}
